name: Build Mac

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: "./src-tauri -> target"

    - name: Install tauri CLI
      run: cargo install tauri-cli

    - name: Install packages
      run: npm i

    - name: Build x86_64
      run: cargo tauri build --target x86_64-apple-darwin

    - name: Build aarch64
      run: rustup target add aarch64-apple-darwin && cargo tauri build --target aarch64-apple-darwin
    
    - name: Upload artifact x86_64
      uses: actions/upload-artifact@v3
      with:
        name: app-darwin-86_64
        path: src-tauri/target/x86_64-apple-darwin/release/bundle

    - name: Upload artifact aarch64
      uses: actions/upload-artifact@v3
      with:
        name: app-darwin-aarch64
        path: src-tauri/target/aarch64-apple-darwin/release/bundle
